inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'

Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
